include:
  - local: '.gitlab/workflows/backend-pipeline.yml'
  - local: '.gitlab/workflows/frontend-admin-pipeline.yml'
  - local: '.gitlab/workflows/frontend-user-pipeline.yml'

stages:
  - build
  - test
  - security
  - docker
  - deploy

variables:
  # Global variables
  DOCKER_REGISTRY: ${CI_REGISTRY}
  ENVIRONMENT: development

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        ENVIRONMENT: production
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        ENVIRONMENT: staging
    - if: $CI_COMMIT_BRANCH == "features/develop"
      variables:
        ENVIRONMENT: development
